"""Deployment-image canonical-byte gate for P0-4.

The fixture is committed bytes (not generated by the container's Pillow), so
this checks the deployed OpenCV wheel and canonicalization code together.
"""
import argparse
import base64
import hashlib
import json

from image_canonical import CANONICALIZATION_VERSION, canonicalize


FIXTURE_B64 = (
    "/9j/4AAQSkZJRgABAQAAAQABAAD/4QAiRXhpZgAATU0AKgAAAAgAAQESAAMAAAABAAYA"
    "AAAAAAD/2wBDAAMCAgMCAgMDAgMDAwMDBAcFBAQEBAkGBwUHCgkLCwoJCgoMDREO"
    "DAwQDAoKDhQPEBESExMTCw4UFhQSFhESExL/2wBDAQMDAwQEBAgFBQgSDAoMEhIS"
    "EhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhL/"
    "wAARCAADAAQDAREAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcI"
    "CQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEI"
    "I0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZ"
    "WmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2"
    "t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEA"
    "AwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3"
    "AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRom"
    "JygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaH"
    "iImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna"
    "4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD0n4P+ELG98IjURc65ZXGp"
    "zefdLpuu3ljE7iOOMERQypGuEjRRhRwoHaozLIcozKVOWMwdKfJHljenBqMeaUrR"
    "XLaKcpSm0rXnKUneUm3yRxFaN2pu71bu7yl1lJ7znJ+9Ocm5zk3OcpSbb//Z"
)
EXPECTED_VERSION = "canon-v1;cv2==5.0.0;jpeg_q=95"
EXPECTED_SHA256 = "ccb92d5c6df548442a59cd71f2a41971177b679216e571a1b3f6de811d7b6748"


def compute():
    result = canonicalize(base64.b64decode(FIXTURE_B64))
    actual = hashlib.sha256(result.data).hexdigest()
    return {"version": CANONICALIZATION_VERSION, "sha256": actual}


def is_expected(measured=None):
    """Return whether a measured deployment result matches the reviewed gate.

    Keep this comparison beside the immutable fixture and expected values.  A
    health endpoint comparing two values derived from the same runtime module
    would be a tautology: it could report success even when the produced bytes
    no longer match the reviewed golden hash.
    """
    measured = compute() if measured is None else measured
    return (measured.get("version") == EXPECTED_VERSION
            and measured.get("sha256") == EXPECTED_SHA256)


def verify():
    measured = compute()
    if not is_expected(measured):
        if measured["version"] != EXPECTED_VERSION:
            raise SystemExit(
                "canonicalization version mismatch: " + measured["version"])
        raise SystemExit("canonicalization golden mismatch: " + measured["sha256"])
    return measured


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true")
    parser.parse_args()
    print(json.dumps(verify(), sort_keys=True))
